<h1>Data Assessment - Ecommerce Platform</h1>

<h4>Dirty Data --> Per Table</h4>
<li>Duplicated Data</li>
<li>Missing Data</li>
<li>Corrupt Data</li>
<li>Inaccurate Data</li>

<h4>Messy Data --> Per Table</h4>
<li>Rule 1: Each Variable Forms a Column</li>
<li>Rule 2: Each Observation Forms a Row</li>
<li>Rule 3: Each Observational Unit Forms a Table</li>

<h4>Manual Assessment</h4>
<li>Spelling Mistakes</li>
<li>Missing Values</li>
<li>Column Problems</li>

<h4>Automatic Assessment</h4>
<li>head()</li>
<li>tail()</li>
<li>sample()</li>
<li>isnull()</li>
<li>info()</li>
<li>duplicated()</li>
<li>describe()</li>

In [1]:
import pandas as pd

In [3]:
df_brands = pd.read_csv('/content/datasets/brands.csv')
df_categories = pd.read_csv('/content/datasets/categories.csv')
df_customer_addresses = pd.read_csv('/content/datasets/customer_addresses.csv')
df_customers = pd.read_csv('/content/datasets/customers.csv')
df_departments = pd.read_csv('/content/datasets/departments.csv')

df_employees = pd.read_csv('/content/datasets/employees.csv')
df_inventory = pd.read_csv('/content/datasets/inventory.csv')
df_order_items = pd.read_csv('/content/datasets/order_items.csv')
df_order_management = pd.read_csv('/content/datasets/order_management.csv')
df_orders = pd.read_csv('/content/datasets/orders.csv')

df_payments = pd.read_csv('/content/datasets/payments.csv')
df_product_promotions = pd.read_csv('/content/datasets/product_promotions.csv')
df_products = pd.read_csv('/content/datasets/products.csv')
df_promotions = pd.read_csv('/content/datasets/promotions.csv')
df_returns = pd.read_csv('/content/datasets/returns.csv')

df_reviews = pd.read_csv('/content/datasets/reviews.csv')
df_sales_targets = pd.read_csv('/content/datasets/sales_targets.csv')
df_shipments = pd.read_csv('/content/datasets/shipments.csv')
df_suppliers = pd.read_csv('/content/datasets/suppliers.csv')
df_warehouses = pd.read_csv('/content/datasets/warehouses.csv')

In [5]:
from ydata_profiling import ProfileReport
profile_report = ProfileReport(df_brands)
profile_report.to_file('brands-output.html')

/tmp/ipykernel_4998/2394318910.py:1: DeprecationWarning:
    `import ydata_profiling` is deprecated and will not receive more updates.
    Please install fg-data-profiling via `pip install fg-data-profiling` and use `import data_profiling` instead.

  from ydata_profiling import ProfileReport

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

100%|██████████| 3/3 [00:00<00:00, 46.89it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [9]:
df_brands.head(10)

   brand_id brand_name      country
0         1      Apple        China
1         2    Samsung        India
2         3     Lenovo  South Korea
3         4       Dell        China
4         5         HP        China
5         6       Nike        India
6         7     Adidas  South Korea
7         8       Puma  South Korea
8         9       Sony          USA
9        10         LG       France

In [10]:
df_brands.tail(10)

    brand_id brand_name      country
90        91   Brand_91  South Korea
91        92   Brand_92      Germany
92        93   Brand_93        India
93        94   Brand_94        India
94        95   Brand_95        Japan
95        96   Brand_96        China
96        97   Brand_97  South Korea
97        98   Brand_98  South Korea
98        99   Brand_99          USA
99       100  Brand_100        China

In [11]:
df_brands.sample(10)

    brand_id brand_name      country
88        89   Brand_89       France
66        67   Brand_67  South Korea
26        27   Brand_27          USA
11        12       Boat      Germany
18        19     Nestle        China
3          4       Dell        China
38        39   Brand_39        China
44        45   Brand_45      Germany
2          3     Lenovo  South Korea
43        44   Brand_44  South Korea

In [16]:
df_brands.isnull().sum()

brand_id      0
brand_name    0
country       0
dtype: int64

In [17]:
df_brands.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   brand_id    100 non-null    int64
 1   brand_name  100 non-null    object
 2   country     100 non-null    object
dtypes: int64(1), object(2)
memory usage: 2.5+ KB

In [35]:
df_brands[df_brands.duplicated()]

Empty DataFrame
Columns: [brand_id, brand_name, country]
Index: []

In [33]:
df_brands['country'].value_counts().sort_values(ascending=False)

country
South Korea    18
India          17
Germany        17
China          14
USA            14
France         14
Japan           6
Name: count, dtype: int64

<h3>DataFrames Information using info()</h3>

In [45]:
df_categories.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 3 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   category_id         50 non-null     int64
 1   category_name       50 non-null     object
 2   parent_category_id  40 non-null     float64
dtypes: float64(1), int64(1), object(1)
memory usage: 1.3+ KB

In [46]:
df_customer_addresses.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   address_id      8000 non-null   int64
 1   customer_id     8000 non-null   int64
 2   address_type    8000 non-null   object
 3   address_line_1  8000 non-null   object
 4   address_line_2  8000 non-null   object
 5   city            8000 non-null   object
 6   state           8000 non-null   object
 7   country         8000 non-null   object
 8   postal_code     8000 non-null   int64
dtypes: int64(3), object(6)
memory usage: 562.6+ KB

In [47]:
df_customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        5000 non-null   int64
 1   first_name         5000 non-null   object
 2   last_name          5000 non-null   object
 3   email              5000 non-null   object
 4   phone              5000 non-null   int64
 5   gender             5000 non-null   object
 6   birth_date         5000 non-null   object
 7   registration_date  5000 non-null   object
 8   loyalty_points     5000 non-null   int64
dtypes: int64(3), object(6)
memory usage: 351.7+ KB

In [48]:
df_departments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   department_id    5 non-null      int64
 1   department_name  5 non-null      object
dtypes: int64(1), object(1)
memory usage: 212.0+ bytes

In [49]:
df_employees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   employee_id    500 non-null    int64
 1   department_id  500 non-null    int64
 2   first_name     500 non-null    object
 3   last_name      500 non-null    object
 4   email          500 non-null    object
 5   hire_date      500 non-null    object
 6   salary         500 non-null    float64
dtypes: float64(1), int64(2), object(4)
memory usage: 27.5+ KB

In [50]:
df_inventory.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   inventory_id        10000 non-null  int64
 1   product_id          10000 non-null  int64
 2   warehouse_id        10000 non-null  int64
 3   quantity_available  10000 non-null  int64
 4   reorder_level       10000 non-null  int64
 5   last_updated        10000 non-null  object
dtypes: int64(5), object(1)
memory usage: 468.9+ KB

In [51]:
df_order_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150423 entries, 0 to 150422
Data columns (total 6 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   order_item_id  150423 non-null  int64
 1   order_id       150423 non-null  int64
 2   product_id     150423 non-null  int64
 3   quantity       150423 non-null  int64
 4   unit_price     150423 non-null  float64
 5   subtotal       150423 non-null  float64
dtypes: float64(2), int64(4)
memory usage: 6.9 MB

In [52]:
df_order_management.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 69802 entries, 0 to 69801
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   management_id  69802 non-null  int64
 1   order_id       69802 non-null  object
 2   employee_id    69802 non-null  object
 3   action_date    69801 non-null  object
 4   action_type    69801 non-null  object
dtypes: int64(1), object(4)
memory usage: 2.7+ MB

In [55]:
df_order_management[df_order_management['action_date'].isnull()]

       management_id    order_id employee_id action_date action_type
50000              1  2022-07-18     Created         NaN         NaN

In [53]:
df_orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      50000 non-null  int64
 1   customer_id   50000 non-null  int64
 2   order_date    50000 non-null  object
 3   order_status  50000 non-null  object
 4   total_amount  50000 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 1.9+ MB

In [54]:
df_payments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   payment_id      50000 non-null  int64
 1   order_id        50000 non-null  int64
 2   payment_date    50000 non-null  object
 3   payment_method  50000 non-null  object
 4   payment_status  50000 non-null  object
 5   amount          50000 non-null  float64
dtypes: float64(1), int64(2), object(3)
memory usage: 2.3+ MB

In [57]:
df_product_promotions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4396 entries, 0 to 4395
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    4396 non-null   int64
 1   promotion_id  4396 non-null   int64
dtypes: int64(2)
memory usage: 68.8 KB

In [58]:
df_products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   product_id     2000 non-null   int64
 1   category_id    2000 non-null   int64
 2   brand_id       2000 non-null   int64
 3   supplier_id    2000 non-null   int64
 4   product_name   2000 non-null   object
 5   description    2000 non-null   object
 6   cost_price     2000 non-null   float64
 7   selling_price  2000 non-null   float64
 8   launch_date    2000 non-null   object
 9   active_status  2000 non-null   bool
dtypes: bool(1), float64(2), int64(4), object(3)
memory usage: 142.7+ KB

In [59]:
df_promotions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   promotion_id      10 non-null     int64
 1   promotion_name    10 non-null     object
 2   start_date        10 non-null     object
 3   end_date          10 non-null     object
 4   discount_percent  10 non-null     int64
dtypes: int64(2), object(3)
memory usage: 532.0+ bytes

In [60]:
df_returns.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3603 entries, 0 to 3602
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   return_id      3603 non-null   int64
 1   order_id       3603 non-null   int64
 2   product_id     3603 non-null   int64
 3   return_date    3603 non-null   object
 4   reason         3603 non-null   object
 5   refund_amount  3603 non-null   float64
dtypes: float64(1), int64(3), object(2)
memory usage: 169.0+ KB

In [61]:
df_reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10433 entries, 0 to 10432
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   review_id    10433 non-null  int64
 1   customer_id  10433 non-null  int64
 2   product_id   10433 non-null  int64
 3   rating       10433 non-null  int64
 4   review_text  10433 non-null  object
 5   review_date  10433 non-null  object
dtypes: int64(4), object(2)
memory usage: 489.2+ KB

In [62]:
df_sales_targets.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6000 entries, 0 to 5999
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   target_id      6000 non-null   int64
 1   employee_id    6000 non-null   int64
 2   target_month   6000 non-null   int64
 3   target_year    6000 non-null   int64
 4   target_amount  6000 non-null   float64
dtypes: float64(1), int64(4)
memory usage: 234.5 KB

In [63]:
df_shipments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   shipment_id      50000 non-null  int64
 1   order_id         50000 non-null  int64
 2   warehouse_id     50000 non-null  int64
 3   shipped_date     50000 non-null  object
 4   delivery_date    50000 non-null  object
 5   shipping_cost    50000 non-null  float64
 6   tracking_number  50000 non-null  object
dtypes: float64(1), int64(3), object(3)
memory usage: 2.7+ MB

In [64]:
df_suppliers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   supplier_id     200 non-null    int64
 1   supplier_name   200 non-null    object
 2   contact_person  200 non-null    object
 3   email           200 non-null    object
 4   phone           200 non-null    int64
 5   city            200 non-null    object
 6   state           200 non-null    object
 7   country         200 non-null    object
dtypes: int64(2), object(6)
memory usage: 12.6+ KB

In [65]:
df_warehouses.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   warehouse_id    20 non-null     int64
 1   warehouse_name  20 non-null     object
 2   city            20 non-null     object
 3   state           20 non-null     object
 4   country         20 non-null     object
dtypes: int64(1), object(4)
memory usage: 932.0+ bytes

Column Problems:
1. Customer —> Registration_date —> Column Should Be of Datetime Type.
2. Employee —> hire_date —> Column Should Be of Datetime Type.
3. Inventory —> last_updated —> Column Should Be of Datetime Type.
4. Order Management —> action_date —> Column Should Be of Datetime Type.
5. Orders —> order_date —> Column Should Be of Datetime Type.
6. Payments —> payment_date —> Column Should Be of Datetime Type.
7. Products —> launch_date —> Column Should Be of Datetime Type.
8. Promotions —> start_date —> Column Should Be of Datetime Type.
9. Promotions —> end_date —> Column Should Be of Datetime Type.
10. Returns —> return_date —> Column Should Be of Datetime Type.
11. Reviews —> review_date —> Column Should Be of Datetime Type.
12. Shipments —> shipped_date —> Column Should Be of Datetime Type.
13. Shipments —> delivery_date —> Column Should Be of Datetime Type.